name: dotnet-backend
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]    
env:
  PROJECT_PATH: ./src/backend/dotnet/lambda/
jobs:
  publish-artifact:
    name: Publish Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: ${{ env.PROJECT_PATH }}
      run: dotnet restore
    - name: Build
      working-directory: ${{ env.PROJECT_PATH }}
      run: dotnet build --no-restore
    - name: Test
      working-directory: ${{ env.PROJECT_PATH }}
      run: dotnet test --no-build --verbosity normal
    - name: Publish Artifacts 
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --no-restore -o publish
    - name: Running some Linux Commands
      run: |
        mkdir zips
        ls
    - name: Setup Zip
      uses: montudor/action-zip@v1
    - name: Zip Artifacts
      run: zip -qq -r zips/lambda.zip publish
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Upload to AWS S3
      run: |
        aws s3 cp zips/lambda.zip s3://serverlesshero-releases/dotnet/lambda/release.zip
